### ISSUE TITLE
'esphome.components.display' has no attribute 'DisplayBufferRef'

### ISSUE THREAD

**Issue by naamah75** [tiaanv/esphome-components#8]
ESPHome 2023.8.3

```
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 1023, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 1010, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/esphome/esphome/__main__.py", line 441, in command_run
    exit_code = write_cpp(config)
  File "/esphome/esphome/__main__.py", line 185, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 197, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 626, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 177, in wrapped
    await coro(conf)
  File "/config/esphome/.esphome/external_components/15342b1e/components/t547/display.py", line 43, in to_code
    config[CONF_LAMBDA], [(display.DisplayBufferRef, "it")], return_type=cg.void
AttributeError: module 'esphome.components.display' has no attribute 'DisplayBufferRef'
```

**Comment by Cadair** [comment]
See #7

**Comment by guillempages** [comment]
> See #7

Or #9 for an updated version with backwards compatibility

Also, in ESPHome 2023.12.0 there will be a new breaking change; #10 should fix that (and include the fix for the missing DisplayBufferRef as well).
